<?php
/** @var \Mastering\SampleModule\Block\Hello $block */
?>

<?php foreach ($block->getItems() as $item) : ?>
    <p>
        <?php echo $item->getName(); ?> : <?php echo $item->getId(); ?> : <?php echo $item->getPrice(); ?>
        : <?php echo $item->getWeight(); ?>
        : <?php echo $item->getImage(); ?>
        : <?php echo $item->getImageUrl(); ?>
        : <?php echo $item->getPrice(); ?>
        :::::::::::::<?php echo $item->getData('meta_description'); ?>
    </p>
<?php endforeach;?>

<?php foreach ($block->getItems() as $item) : ?>
<p>
    <?php var_dump($item->getData())?>
    <?php endforeach;?>


