<?php $productCollection = $block->getProductCollection(); ?>
<?php $imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct'); ?>
<?php if (count($productCollection)): ?>
    <?php foreach ($productCollection as $product): ?>
        <div class="block1">
        <?php $productImage = $imageBlock->getImage($product, 'category_page_grid'); ?>
        <h1>Product name : <?php echo $product->getName(); ?></h1>
        <h1>Product price : <?php echo $product->getPrice(); ?></h1>
        <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1"><?php echo $productImage->toHtml(); ?></a>
        </div>
    <?php endforeach; ?>
<?php endif; ?>