<?php
/** @var \Akulov\SliderModule\Block\Slider $block */
?>

<div class="slideshow-container">
    <?php foreach ($block->getItems() as $item) : ?>
        <div class="mySlides fade">
            <div class="numbertext"><?php echo $item->getId(); ?> / 3</div>
            <?php echo '<img src="http://magento2pro.loc/media/slider/'.$item->getImage().'" style="width:100%">'; ?>
            <div class="text"><?php echo $item->getDiscription(); ?></div>
        </div>
    <?php endforeach;?>
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>

<br>

<div style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
</div>

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) {slideIndex = 1}
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";
        dots[slideIndex-1].className += " active";
    }
</script>
